version: '3.4'

services:
  eparafia.api:
    container_name: "Eparafia.Parish.API"
    image: ${DOCKER_REGISTRY-}eparafiaapi
    ports:
      - 5002:80
    build:
      context: .
      dockerfile: Eparafia.Parish.API/Dockerfile

  eparafia.identity.api:
    container_name: "Eparafia.Identity.API"
    image: ${DOCKER_REGISTRY-}eparafiaidentityapi
    ports:
      - 5001:80
    build:
      context: .
      dockerfile: Eparafia.Identity.API/Dockerfile
  #eparafia.bible.api:
  #  container_name: "BibleAPI"
  #  image: ${DOCKER_REGISTRY-}eparafiabibleapi
  #  ports:
  #    - 5003:80
  #  build:
  #    context: .
  #    dockerfile: Eparafia.Bible.API/Dockerfile
  #
