version: '3.4'

services:
<<<<<<< HEAD
=======
  #rabbitmq:
  #  image: rabbitmq:3-management-alpine
  #  container_name: 'RabbitMQ'
  #  ports:
  #    - 5672:5672
  #    - 15672:15672
  #  environment:
  #    - "RABBITMQ_DEFAULT_PASS=!Malinka@pass"
  #    - "RABBITMQ_DEFAULT_USER=Eparafia"
  #  volumes:
  #    - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #    - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

>>>>>>> main
  eparafia.api:
    container_name: "Eparafia.Parish.API"
    image: ${DOCKER_REGISTRY-}eparafiaapi
    ports:
      - 5002:80
    build:
      context: .
      dockerfile: Eparafia.Parish.API/Dockerfile

  eparafia.identity.api:
    container_name: "Eparafia.Identity.API"
    image: ${DOCKER_REGISTRY-}eparafiaidentityapi
    ports:
      - 5001:80
    build:
      context: .
      dockerfile: Eparafia.Identity.API/Dockerfile
  #eparafia.bible.api:
  #  container_name: "BibleAPI"
  #  image: ${DOCKER_REGISTRY-}eparafiabibleapi
  #  ports:
  #    - 5003:80
  #  build:
  #    context: .
  #    dockerfile: Eparafia.Bible.API/Dockerfile
  #
