// <auto-generated />
using System;
using Eparafia.Administration.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eparafia.Administration.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230430153533_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismEntities.BaptismClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BaptismRegisterId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BaptismRegisterId")
                        .IsUnique();

                    b.ToTable("_baptismClients");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismFather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BaptismParentsRelationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CityOfBirth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Confession")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BaptismParentsRelationId")
                        .IsUnique();

                    b.ToTable("_fathers");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismGodfather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BaptismRegisterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CityOfBirth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Confession")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BaptismRegisterId")
                        .IsUnique();

                    b.ToTable("_godfathers");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismGodmother", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BaptismRegisterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CityOfBirth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Confession")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BaptismRegisterId")
                        .IsUnique();

                    b.ToTable("_godmothers");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismMother", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BaptismParentsRelationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CityOfBirth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Confession")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BaptismParentsRelationId")
                        .IsUnique();

                    b.ToTable("_mothers");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismParentsRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BaptismRegisterId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FatherId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MotherId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ParentRelation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("_baptismParentsRelations");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActIdId")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfSacrament")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GodfatherId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GodmotherId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParentsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParishId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SacramentalMakerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ActIdId");

                    b.HasIndex("ParentsId")
                        .IsUnique();

                    b.HasIndex("ParishId");

                    b.HasIndex("SacramentalMakerId");

                    b.ToTable("_baptismRegisters");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.DeadClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid>("DeadRegisterId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeadRegisterId")
                        .IsUnique();

                    b.ToTable("_deadClients");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.DeadRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfSacrament")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeadClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParishId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SacramentalMakerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ParishId");

                    b.HasIndex("SacramentalMakerId");

                    b.ToTable("_deadRegisters");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.Men", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("Confession")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("WeddingRegisterId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WeddingRegisterId")
                        .IsUnique();

                    b.ToTable("_weddingMen");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.Parish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CallName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("_parish");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.Priest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ParishId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ParishId");

                    b.ToTable("Priest");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.SacramentalMaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("_sacramentalMaker");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.WeddingRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfSacrament")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MenId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParishId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SacramentalMakerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WomenId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ParishId");

                    b.HasIndex("SacramentalMakerId");

                    b.ToTable("_weddingRegisters");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.Witness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("Confession")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("WeddingRegisterId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WeddingRegisterId");

                    b.ToTable("_weddingWitness");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.Women", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("Confession")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("WeddingRegisterId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WeddingRegisterId")
                        .IsUnique();

                    b.ToTable("_weddingWomen");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.ValueObjects.ActId", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ActId");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismEntities.BaptismClient", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.BaptismRegister", "BaptismRegister")
                        .WithOne("Client")
                        .HasForeignKey("Eparafia.Administration.Domain.Entities.BaptismEntities.BaptismClient", "BaptismRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaptismRegister");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismFather", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismParentsRelation", "BaptismParentsRelation")
                        .WithOne("Father")
                        .HasForeignKey("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismFather", "BaptismParentsRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Eparafia.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("BaptismFatherId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("BaptismFatherId");

                            b1.ToTable("_fathers");

                            b1.WithOwner()
                                .HasForeignKey("BaptismFatherId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("BaptismParentsRelation");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismGodfather", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.BaptismRegister", "BaptismRegister")
                        .WithOne("Godfather")
                        .HasForeignKey("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismGodfather", "BaptismRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Eparafia.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("BaptismGodfatherId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("BaptismGodfatherId");

                            b1.ToTable("_godfathers");

                            b1.WithOwner()
                                .HasForeignKey("BaptismGodfatherId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("BaptismRegister");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismGodmother", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.BaptismRegister", "BaptismRegister")
                        .WithOne("Godmother")
                        .HasForeignKey("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismGodmother", "BaptismRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Eparafia.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("BaptismGodmotherId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("BaptismGodmotherId");

                            b1.ToTable("_godmothers");

                            b1.WithOwner()
                                .HasForeignKey("BaptismGodmotherId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("BaptismRegister");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismMother", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismParentsRelation", "BaptismParentsRelation")
                        .WithOne("Mother")
                        .HasForeignKey("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismMother", "BaptismParentsRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Eparafia.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("BaptismMotherId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("BaptismMotherId");

                            b1.ToTable("_mothers");

                            b1.WithOwner()
                                .HasForeignKey("BaptismMotherId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("BaptismParentsRelation");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismRegister", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.ValueObjects.ActId", "ActId")
                        .WithMany()
                        .HasForeignKey("ActIdId");

                    b.HasOne("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismParentsRelation", "Parents")
                        .WithOne("BaptismRegister")
                        .HasForeignKey("Eparafia.Administration.Domain.Entities.BaptismRegister", "ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eparafia.Administration.Domain.Entities.Parish", "Parish")
                        .WithMany("BaptismRegisters")
                        .HasForeignKey("ParishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eparafia.Administration.Domain.Entities.SacramentalMaker", "SacramentalMaker")
                        .WithMany("BaptismRegisters")
                        .HasForeignKey("SacramentalMakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActId");

                    b.Navigation("Parents");

                    b.Navigation("Parish");

                    b.Navigation("SacramentalMaker");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.DeadClient", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.DeadRegister", "DeadRegister")
                        .WithOne("DeadClient")
                        .HasForeignKey("Eparafia.Administration.Domain.Entities.DeadClient", "DeadRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeadRegister");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.DeadRegister", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.Parish", "Parish")
                        .WithMany("DeadRegsters")
                        .HasForeignKey("ParishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eparafia.Administration.Domain.Entities.SacramentalMaker", "SacramentalMaker")
                        .WithMany("DeadRegisters")
                        .HasForeignKey("SacramentalMakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parish");

                    b.Navigation("SacramentalMaker");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.Men", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.WeddingRegister", "WeddingRegister")
                        .WithOne("Men")
                        .HasForeignKey("Eparafia.Administration.Domain.Entities.Men", "WeddingRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Eparafia.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("MenId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("MenId");

                            b1.ToTable("_weddingMen");

                            b1.WithOwner()
                                .HasForeignKey("MenId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("WeddingRegister");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.Priest", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.Parish", "Parish")
                        .WithMany("Priests")
                        .HasForeignKey("ParishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parish");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.WeddingRegister", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.Parish", "Parish")
                        .WithMany("WeddingRegisters")
                        .HasForeignKey("ParishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eparafia.Administration.Domain.Entities.SacramentalMaker", "SacramentalMaker")
                        .WithMany("WeddingRegisters")
                        .HasForeignKey("SacramentalMakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parish");

                    b.Navigation("SacramentalMaker");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.Witness", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.WeddingRegister", "WeddingRegister")
                        .WithMany("Witnesses")
                        .HasForeignKey("WeddingRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Eparafia.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("WitnessId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("WitnessId");

                            b1.ToTable("_weddingWitness");

                            b1.WithOwner()
                                .HasForeignKey("WitnessId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("WeddingRegister");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.Women", b =>
                {
                    b.HasOne("Eparafia.Administration.Domain.Entities.WeddingRegister", "WeddingRegister")
                        .WithOne("Women")
                        .HasForeignKey("Eparafia.Administration.Domain.Entities.Women", "WeddingRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Eparafia.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("WomenId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("WomenId");

                            b1.ToTable("_weddingWomen");

                            b1.WithOwner()
                                .HasForeignKey("WomenId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("WeddingRegister");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismParents.BaptismParentsRelation", b =>
                {
                    b.Navigation("BaptismRegister")
                        .IsRequired();

                    b.Navigation("Father")
                        .IsRequired();

                    b.Navigation("Mother")
                        .IsRequired();
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.BaptismRegister", b =>
                {
                    b.Navigation("Client")
                        .IsRequired();

                    b.Navigation("Godfather")
                        .IsRequired();

                    b.Navigation("Godmother")
                        .IsRequired();
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.DeadRegister", b =>
                {
                    b.Navigation("DeadClient")
                        .IsRequired();
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.Parish", b =>
                {
                    b.Navigation("BaptismRegisters");

                    b.Navigation("DeadRegsters");

                    b.Navigation("Priests");

                    b.Navigation("WeddingRegisters");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.SacramentalMaker", b =>
                {
                    b.Navigation("BaptismRegisters");

                    b.Navigation("DeadRegisters");

                    b.Navigation("WeddingRegisters");
                });

            modelBuilder.Entity("Eparafia.Administration.Domain.Entities.WeddingRegister", b =>
                {
                    b.Navigation("Men")
                        .IsRequired();

                    b.Navigation("Witnesses");

                    b.Navigation("Women")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
